### PR TITLE
T-001: scaffold v0.2 portable contract foundation

### LINKED ISSUE #71: v0.2 T-001 — workspace scaffold + frozen contract foundation
## Authority

- Version: `v0.2`
- Task pack: `docs/implementation/v0.2/task-packs/T001_v02_workspace_scaffold_plus_frozen_contract_foundation.md`
- Frozen PRD: `docs/product/DomainHarness_v0.2_PRD_FROZEN.md`
- Frozen L2: `docs/architecture/DomainHarness_v0.2_L2_ARCHITECTURE_EVIDENCE.md`
- Standard revision: `0446f04583f6cf464c835f26e2f657c8b703cb4e`

## Execution identity

- Base: `9a9323a47f4bdcb9df34981c4c705a3349437b91`
- Branch: `v0.2_t001`
- Current head: `4dfc4a7956ef3fbdcd950aade65204b929202bec`
- PR base: `v0.2`

## Scope

Freeze the v0.2 monorepo package skeleton and portable contract foundation only. Do not implement compiler/store/runtime behavior owned by later tasks.

Current implementation includes:

- four-package workspace skeleton (`domain-harness`, compiler, Node host, Expo host);
- portable v0.2 contract family under `packages/domain-harness/src/v2/`;
- WorkflowAddress/lifecycle, Durable Domain Message ACK/disposition, RuntimeStore semantic contract, capabilities, package registry, effect/host ports, Query/Projection/Subscription contracts;
- RuntimeStore conformance harness skeleton;
- monorepo-wide build/typecheck/test scripts;
- core package manifest no longer declares `better-sqlite3` or a Node runtime engine.

## Important transitional constraint

The repository still contains frozen v0.1 implementation source under the existing root SDK path, including Node-specific Loader/SQLite/Worker code. T-001 does **not** migrate those implementations because that work belongs to T-002/T-003/T-004/T-006/T-007/T-016. Therefore this issue must not be closed on dependency inspection alone, and this branch must not be represented as a fully portable v0.2 Runtime implementation.

## Validation required before T-001 can be DONE

Run on a clean Build Host against exact task head:

```text
npm ci
npm run lint
npm run typecheck
npm test
npm run build
npm pack -w @kaicreator/domain-harness
```

Also verify:

- `@kaicreator/domain-harness` manifest has no SQLite driver dependency;
- no core → compiler/node/expo workspace dependency edge;
- `./v2` contract API typechecks;
- new workspace skeleton packages build/typecheck;
- existing v0.1 regression is not silently skipped.

## Current validation state

- PASS: v0.2 contract/skeleton TypeScript static checks in the available execution environment.
- PASS: branch diff is exactly ahead of the frozen T-001 base and stays within the planned workspace/contract write set.
- PASS (structural): package-lock workspace synchronization check no longer fails with npm `EUSAGE`.
- ENV-BLOCKED here: full `npm ci` because this execution environment cannot fetch missing npm registry packages; offline attempt reaches `ENOTCACHED` instead of lock mismatch.
- PENDING: clean Build Host commands above.

Close only after exact-SHA Build Host evidence is attached and the T-001 acceptance checklist passes.

### PR DESCRIPTION
**Pull request by kaicreator-mm**
Closes #71 when validation completes.

## Authority

- Frozen PRD: `docs/product/DomainHarness_v0.2_PRD_FROZEN.md`
- Frozen L2: `docs/architecture/DomainHarness_v0.2_L2_ARCHITECTURE_EVIDENCE.md`
- Task pack: `docs/implementation/v0.2/task-packs/T001_v02_workspace_scaffold_plus_frozen_contract_foundation.md`
- Standard revision: `0446f04583f6cf464c835f26e2f657c8b703cb4e`

## Exact execution identity

- Base: `9a9323a47f4bdcb9df34981c4c705a3349437b91`
- Head: `cee4a347e9c93d9681fa1cce0047d090755b1b0e` (reviewed head `4dfc4a7956ef3fbdcd950aade65204b929202bec` + `cee4a34` canonical lockfile regeneration per #73)
- Task branch: `v0.2_t001`
- Base branch: `v0.2`

## Scope implemented

- adds compiler / Node host / Expo host workspace skeletons;
- adds portable v0.2 contract layer under `packages/domain-harness/src/v2/`;
- freezes WorkflowAddress/lifecycle, durable Domain Message ACK/disposition, semantic RuntimeStore, host/capability ports, compiled package/package registry, effect execution, Query/Projection/Subscription contracts;
- adds RuntimeStore conformance harness skeleton and v0.2 API contract test;
- updates root workspace scripts for monorepo-wide build/typecheck/test;
- removes `better-sqlite3` and Node engine declaration from the portable core package manifest, while retaining the driver only as a root development dependency so frozen v0.1 regression code can still execute during the staged migration.

## Dependency direction

Intended frozen direction:

```text
compiler ──→ core contracts
node host ─→ core
expo host ─→ core
core ──────X compiler/node/expo
```

This task creates skeletons/contracts only; later tasks own implementations.

## Transitional constraint

The repository still contains frozen v0.1 implementation source in the existing core tree, including Node-specific Loader/SQLite/Worker code. T-001 intentionally does not migrate it because that work is owned by T-002/T-003/T-004/T-006/T-007/T-016. Therefore this PR does **not** claim the integrated v0.2 Runtime implementation is already portable.

## Validation

Build Host gate at exact head `cee4a34` (clean worktree; evidence detail in #73):

- PASS — `npm ci` (exit 0, 0 vulnerabilities)
- PASS — `npm run lint` (exit 0)
- PASS — `npm run typecheck` (exit 0; all four workspaces)
- PASS — `npm test` (exit 0; 118 tests, 118 pass, 0 skipped — v0.1 regression fully retained)
- PASS — `npm run build` (exit 0; all four workspaces)
- PASS — `npm pack -w @kaicreator/domain-harness` (`./v2` types + output present; no host-workspace content in tarball)
- PASS — dependency boundary: core manifest has only ajv/jsonata/xstate/yaml/zod; `better-sqlite3` is root devDependency only; `npm ls --workspaces` clean
- PASS — `src/v2` isolated typecheck with `types: []` (no `@types/node`) and no Node/SQLite identifiers in public contracts
- PASS — lockfile regenerated canonically: zero registry version drift vs v0.1 baseline, full resolved/integrity/os/cpu/engines/license metadata retained

CI: `ci/woodpecker/pr/verify` fails with a pre-existing, repo-wide Woodpecker agent backend error (`node:22-bookworm` not executable in local/exec backend; pipelines #1–#10 all fail identically including pushes to `main`). Tracked in #74; per `PROJECT_OVERRIDES` the real Node Build Host is final truth for this validation profile.

### CODE REVIEW

**Comment by kaicreator-mm** [comment]
## T-001 independent review checkpoint

**Status: DOING / Draft — not mergeable yet.**

Contract/workspace review is acceptable within T-001 scope, but one merge-blocking hygiene issue was found in the current exact head `4dfc4a7956ef3fbdcd950aade65204b929202bec`:

- the offline-synchronized `package-lock.json` removes substantial npm-generated `resolved` / `integrity` / platform / engine metadata and creates ~1200 lines of avoidable lockfile churn.

This is not an architecture contradiction and does not require product/L2 change. It must be corrected by normal npm lockfile regeneration on a connected Build Host.

Validation/fix handoff: #73.

After #73 produces a new exact head, rerun the complete clean gate (`npm ci`, lint, typecheck, test, build, pack), then re-review the new diff before this PR is marked ready. No T-002+ implementation should be pulled into this PR.

**Comment by kaicreator-mm** [comment]
Build Host validation complete — full gate PASS at exact head `cee4a347e9c93d9681fa1cce0047d090755b1b0e` (clean worktree, Node v26.8.1 / npm 11.19.0). Detailed evidence: #73 (issuecomment-5724197305).

Summary:

- lockfile canonically regenerated (`npm install --package-lock-only --ignore-scripts`, seeded from the v0.2 baseline lock so npm preserves v0.1-era pins) — zero registry version drift, 80 integrity entries, full platform metadata retained; `npm outdated` empty
- V1–V6 all exit 0: `npm ci` / `lint` / `typecheck` (4 workspaces) / `test` (118/118, v0.1 regression fully retained, 0 skipped) / `build` (4 workspaces) / `npm pack` (`./v2` js+d.ts present, no host-workspace content)
- dependency boundary: core deps = ajv/jsonata/xstate/yaml/zod only; `better-sqlite3` root-dev only; no core→host edges, no cycles
- `src/v2` typechecks isolated without `@types/node`; no SQLite/Worker/node:* in public contracts
- woodpecker CI check fails for a pre-existing repo-wide agent-backend reason (also fails on `main` pushes) — tracked in #74, not a T-001 defect

PR marked ready for review per #73 closeout criteria.

**Comment by kaicreator-mm** [comment]
## ChatGPT final T-001 review

Build Host validation at exact head `cee4a347e9c93d9681fa1cce0047d090755b1b0e` is accepted as PASS: clean `npm ci`, lint, typecheck, 118/118 tests, build, pack, dependency-boundary inspection, isolated `src/v2` typecheck, and canonical lockfile regeneration are all evidenced in #73.

The failing Woodpecker status is not treated as a T-001 code regression because #74 demonstrates the same `node:22-bookworm` local/exec-backend failure across repository history, including pre-v0.2/main commits.

### Remaining T-001 closeout blocker

The frozen T-001 Task Pack marks L3 REQUIRED and explicitly requires at least one negative/crash/race fixture appropriate to the task risk, plus `host adapter interface contracts and test fakes` as a deliverable. At current head:

- `packages/domain-harness/tests/v2-contracts.test.ts` is a positive smoke/type sentinel only;
- `tests/helpers/runtime-store-conformance.ts` is a conformance helper skeleton, not a host adapter fake;
- existing v0.1 crash/negative regression is valuable regression coverage but does not encode the new T-001 portability/dependency boundary.

Minimal acceptable fix, still within T-001 write set:

1. add a deterministic negative/boundary test that fails if portable `@kaicreator/domain-harness` v0.2 contracts/package metadata acquire Node built-ins, `better-sqlite3`, or core -> compiler/node/expo dependency edges; and
2. add a minimal reusable `RuntimeHostBindings` test fake/helper for downstream tasks.

Do not implement any T-002+ behavior. After the minimal test/helper commit, rerun the complete exact-head Build Host gate from `npm ci` through `npm pack` and attach evidence. Until then T-001 is REVIEW-BLOCKED, not DONE.

**Comment by kaicreator-mm** [comment]
T-001 final Review blockers resolved at `dad165d238840903d029ac2d69900879ea827611`.

- negative portable/dependency boundary fixture added (`tests/v2-boundaries.test.ts`) — deny-list scan of `src/v2` + core manifest dependency-edge check; effectiveness proven by planting a `better-sqlite3` token and observing the fixture FAIL, then removing it
- reusable `RuntimeHostBindings` test fake added (`tests/helpers/runtime-host-fake.ts`, `createRuntimeHostFake(overrides?)`) — deterministic, no I/O/SQLite/HTTP/Worker/jsonata, ports overridable
- fake behavior tests added (`tests/v2-host-fake.test.ts`), written test-first (failed on missing helper before the helper existed)
- full clean Build Host gate rerun on exact HEAD `dad165d`: `npm ci` / lint / typecheck / test (**122 passed, 0 failed, 0 skipped**) / build / pack all PASS
- v0.1 regression retained in full (118 pre-existing tests)
- no T-002+ implementation added; diff is 3 files / +184 lines, all under `packages/domain-harness/tests/**`

Evidence: #73 (issuecomment-5724327740)

**Review by kaicreator-mm — COMMENTED** [review]
REVIEW_RESULT — PASS

Exact HEAD: `dad165d238840903d029ac2d69900879ea827611`

T-001 final review is PASS. The previous closeout blockers are resolved within the declared T-001 write set: (1) deterministic portability/dependency negative-boundary fixtures are present and exercised; (2) a reusable deterministic `RuntimeHostBindings` test fake is present and tested. The fix commit adds only three files under `packages/domain-harness/tests/**` and does not implement T-002+ behavior.

Exact-head Build Host evidence in #73 records: `npm ci`, lint, typecheck, test (122/122, 0 skipped), build, and pack all PASS; v0.1 regression remains retained; canonical lockfile and core dependency boundaries remain unchanged. Woodpecker remains a separately tracked infrastructure failure in #74 and is not evidence of a T-001 code regression.

No remaining T-001 blocker found. PR is acceptable to merge into `v0.2`.
